import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Navbar from "@/components/navbar/Navbar";

const poppins = Poppins({subsets: ["latin"], weight: "400"});

export const metadata: Metadata = {
  title: "Find Work New Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        <div className={`flex bg-gray-50 text-gray-900 w-full min-h-screen`}>
            <Sidebar />
            <main className={"flex flex-col w-full h-[100vh] py-2 pr-2 pl-[282px]"}>
                <Navbar />
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
